module.exports = {
  sumoDir: '.sumo',
  baselineDir: '.sumo/baseline',
  killedDir: '.sumo/killed',
  liveDir: '.sumo/live',
  redundantDir: '.sumo/redundant',
  equivalentDir: '.sumo/equivalent',
  stillbornDir: '.sumo/stillborn',
  timedoutDir: '.sumo/timedout',
  mutantsDir: '.sumo/mutants',
  projectDir: '',
  buildDir: '',
  contractsDir: '',
  skipContracts: [''],
  testingTimeOutInSec: 3000,
  bail: false,
  ganache: true,
  customTestScript: false,
  optimized: true,
  tce: true,
  contractsGlob: '/**/*.sol',
  packageManagerGlob: ['/package-lock.json', '/yarn.lock'],
  testGlob: ['/test/**/*.js', '/test/**/*.sol,', '/test/**/*.ts'
  ]
}
